Add dev-CI
k3ilona/publisher-slack-bot pull request #30
Opened 2024-01-28 13:44 UTC by dm-ol

2024-01-28 14:13 UTC, vit-um commented
make: *** [Makefile:72: push] Error 1
Error: Process completed with exit code 2.

Тут помилка через відсутність дозволу та виконання команди, перед виконанням `make push`  потрібно авторизуватись в режестрі:
```sh
$ export CR_PAT=ghp_*****************
$ echo $CR_PAT \| docker login ghcr.io -u vit-um --password-stdin

 Login Succeeded
```

2024-01-28 20:42 UTC, vit-um approved these changes

2024-01-28 21:02 UTC, Andygol commented on helm/templates/deployment.yaml
>            image: {{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag }}-{{ .Values.image.os }}-{{ .Values.image.arch }}
Тут, потрібно виправити формат теґу образу

2024-01-28 21:17 UTC, Andygol commented on helm/Chart.yaml
> +appVersion: "0.1.2"
Версія застосунку має оновлюватись через СІ

2024-01-28 21:29 UTC, Andygol requested changes
Потрібне доопрацювання Helm-чарту та створення СІ для заміни версії застосунку в чарті

2024-01-28 22:00 UTC, Andygol requested changes

2024-01-28 22:00 UTC, Andygol commented on .github/workflows/ci.yaml
> +      run: make clean
Оновлення версії застосунку в Helm-чарті

```suggestion
      run: make clean
      
  helm:
    name: DEV-HELM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Define tag
      run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Define version
      run: echo "VERSION=$TAG-${{ github.ref }}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: |
          yq -i '.image.version = strenv(VERSION) helm/values.yaml' 
          yq -i '.appVersion = strenv(TAG) helm/Chart.yaml'
```

2024-01-28 22:03 UTC, vit-um approved these changes

2024-01-28 22:06 UTC, vit-um approved these changes

2024-01-28 22:13 UTC, Andygol commented on cmd/ilonabot.go
> +		attachment.Color = "#3d3d3d"
Можна зробити відповіді бота менш сабмісівними
```suggestion
		attachment.Text = fmt.Sprintf("%s, слухаю уважно 😙💨", user.RealName)
		attachment.Pretext = "🥱, а? Шо, щось сталося?"
		attachment.Color = "#3d3d3d"
```

2024-01-29 10:14 UTC, vit-um approved these changes

2024-01-29 11:34 UTC, Andygol commented on .github/workflows/ci.yaml
> +      run: echo "VERSION=$TAG-dev-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
Щоб не хардкодити бранч можна внести наступні зміни @dm-ol 

```suggestion
      run: echo "VERSION=$TAG-${{ github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
```

2024-01-29 13:02 UTC, Andygol commented
Пропоную закрити цей PR без злиття. 

Для злиття в гілку `main` створити окремий PR, коли буде готовий реліз

2024-01-29 19:17 UTC, Andygol commented
Закриваю цей ПР без злиття

2024-01-29 19:17 UTC, closed without merging